package it.unipi.rcl.project.common;

/**
 * Enum that encodes the error messages that can be generated by
 * the client's requests to the server.
 */

public enum ErrorMessage {
	AlreadyFollowed,
	AlreadyVoted,
	CommentingOwnPost,
	FollowingYourself,
	InvalidCommand,
	InvalidPassword,
	InvalidPostId,
	InvalidTags,
	InvalidUserId,
	InvalidUsername,
	NoSuchUser,
	NotFollowing,
	RewinningOwnPost,
	Success,
	UserAlreadyExists,
	UserAlreadyLoggedIn,
	UserNotLoggedIn,
	UserNotAuthor,
	UnknownError,
	VoterIsAuthor
}
