package it.unipi.rcl.project.client;

import javax.swing.*;
import java.awt.*;

/**
 * Class that implements a customisable popup alert window
 */
public class AlertForm extends Form {
	private JPanel panel;
	private JLabel textLabel;
	private JButton okButton;

	/**
	 * The parameters are not the strings that will be shown, they are resourceBundle keys
	 */
	public AlertForm(String title, String label, String button) {
		super(null);
		JFrame frame = new JFrame();
		frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		frame.setContentPane(panel);
		frame.setVisible(true);
		frame.setSize(400, 200);

		frame.setTitle(resourceBundle.getString(title));
		textLabel.setText(resourceBundle.getString(label));
		okButton.setText(resourceBundle.getString(button));

		okButton.addActionListener(actionEvent -> frame.dispose());
		Form.centerFrame(frame);
	}

	@Override
	public JPanel getPanel() {
		return panel;
	}

	/**
	 * Factory methods.
	 */

	public static void errorAlert(String message) {
		new AlertForm("error", message, "ok");
	}

	public static void errorAlert() {
		errorAlert("error.unknown");
	}

	public static void successAlert(String message) {
		new AlertForm("success", message, "ok");
	}

	public static void followAlert(String username) {
		AlertForm a = new AlertForm("notification", "followed.you", "ok");
		a.textLabel.setText(username + " " + resourceBundle.getString("followed.you"));
	}

	public static void unfollowAlert(String username) {
		AlertForm a = new AlertForm("notification", "unfollowed.you", "ok");
		a.textLabel.setText(username + " " + resourceBundle.getString("unfollowed.you"));
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel = new JPanel();
		panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
		textLabel = new JLabel();
		textLabel.setText("");
		panel.add(textLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		okButton = new JButton();
		okButton.setText("");
		panel.add(okButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel;
	}
}
