package it.unipi.rcl.project.client;

import it.unipi.rcl.project.common.Comment;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.util.Date;

/**
 * Form that displays a single comment.
 */
public class CommentForm extends Form {
	private JLabel usernameLabel;
	private JLabel textLabel;
	private JLabel timestampLabel;
	private JPanel panel;

	public CommentForm(AppEventDelegate aed, Comment comment) {
		super(aed);
		textLabel.setText(makeWrappedText(aed.getFrameWidth() - 40, comment.text));
		timestampLabel.setText(dateFormat.format(new Date(comment.timestamp)));
		usernameLabel.setText(Integer.toString(comment.commenterId));
		ServerProxy.instance.getUsernameFromId(comment.commenterId, username -> usernameLabel.setText(username), errorMessage -> {
		});
	}

	@Override
	public JPanel getPanel() {
		return panel;
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel = new JPanel();
		panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(10, 10, 10, 10), -1, -1));
		panel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
		usernameLabel = new JLabel();
		usernameLabel.setForeground(new Color(-10516293));
		usernameLabel.setText("Label");
		panel.add(usernameLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		textLabel = new JLabel();
		textLabel.setText("Label");
		panel.add(textLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		timestampLabel = new JLabel();
		timestampLabel.setText("Label");
		panel.add(timestampLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel;
	}

}
